---
blank_issues_enabled: false
contact_links:
  - name: 📖 Documentação do Sistema
    url: >-
      https://github.com/andrefontourainvillia/java-copilot-code-agent-exercise/blob/main/docs/README.md
    about: Consulte a documentação completa do sistema antes de abrir uma issue
  - name: 💬 Discussões
    url: >-
      https://github.com/andrefontourainvillia/java-copilot-code-agent-exercise/discussions
    about: Para perguntas gerais e discussões sobre o sistema